config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :posts do
    resources :helpfuls, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/helpful.rb
class Helpful < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many   :helpfuls
  validates :title, presence: true
  validates :watched_on, presence: true
  validates :theater, presence: true
  validates :comment, presence: true
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  def self.search(search)
    if search.present?
      posts = Post.where('title LIKE ?', "%#{search}%")
    else
      posts = Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :helpfuls, dependent: :destroy

  def already_helpfuled?(post)
    self.helpfuls.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resouce)
    user_path(current_user)
  end

  def after_sign_in_path_for(resouce)
    user_path(current_user)
  end

  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :username])
      devise_parameter_sanitizer.permit(:sign_in, keys:[:username])
  end
end

app/controllers/helpfuls_controller.rb
class HelpfulsController < ApplicationController
  def create
    @helpful = current_user.helpfuls.create(post_id: params[:post_id])
    redirect_to root_path
  end
  def destroy
    @helpful = Helpful.find_by(post_id: params[:post_id], user_id: current_user.id)
    @helpful.destroy
    redirect_to root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_user!, only: [:edit, :destroy]

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    post.save!
    redirect_to post_path(post), notice: 'save'
  end

  def index
    @posts = Post.all
  end

  def search
    @posts = Post.search(params[:keyword])
    render :index
  end

  def show
    @post = Post.find(params[:id])
    @helpful = Helpful.new
    @posts_of_the_same_name = Post.where(title: @post.title).where.not(id: @post.id)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update!(post_params)
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy!
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :watched_on, :theater, :comment, :rate)
  end

  def require_current_user!
    post = Post.find(params[:id])
    redirect_to posts_path unless post.user_id == current_user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @posts = user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helpfuls_helper.rb
module HelpfulsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-header">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">ムビログ</a></a>
      </div>
      <div>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li><%= link_to "投稿する", new_post_path %></li>
            <li><%= link_to "みんなの投稿", posts_path %></li>
            <li><%= link_to "じぶんの投稿", user_path(current_user) %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </ul>
          <div class="navbar-right">
          </div>
          <%= form_with url: search_posts_path, method: :get, local: true, class: "navbar-form navbar-right" do |f| %>
            <%= f.text_field :keyword %>
            <%= f.submit :search , class: "btn btn-primary" %>
          <% end %>
          <p class="navbar-text navbar-right">ようこそ <%= current_user.username %> さん。</p>
        <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/homes/top.html.erb
<h1>
  映画感想記録アプリ<br>
  ムビログ
</h1>
<p>
  本アプリケーションでは、<br>
  自分の映画の感想を記録したり、<br>
  他人の映画の感想を検索できます。
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiRecordMovieReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'homes/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>投稿を編集する</h1>
<%= form_with model: @post do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  <div class="field">
    <%= f.label :watched_on %><br />
    <%= f.date_select :watched_on %>
  </div>
  <div class="field">
    <%= f.label :theater %><br />
    <%= f.text_field :theater %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.hidden_field :rate %>
    <div id="star"></div>
  </div>
  <%= f.submit '保存する' %>
<% end %>

<script>
  $(document).on('turbolinks:load', function(){
    $('#star').raty({
      size: 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn:   '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png')%>',
      scoreName: 'post[rate]',
      score: <%= @post.rate %>,
      half: true
    });
  })
</script>

app/views/posts/index.html.erb
<h1>みんなの投稿</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>観賞日</th>
      <th>映画館</th>
      <th>コメント</th>
      <th>評価</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%= post.watched_on %></td>
        <td><%= post.theater    %></td>
        <td><%= post.comment.truncate(13)    %></td>
        <td>
          <div id="star-rate-<%= post.id %>"></div>
          <script>
            $(document).on('turbolinks:load', function(){
              $('#star-rate-<%= post.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn :  '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= post.rate %>,
              });
            });
          </script> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @post do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  <div class="field">
    <%= f.label :watched_on %><br />
    <%= f.date_select :watched_on %>
  </div>
  <div class="field">
    <%= f.label :theater %><br />
    <%= f.text_field :theater %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.hidden_field :rate %>
    <div id="star">
  </div>
  <%= f.submit '投稿する' %>
<% end %>

<script>
  $(document).on('turbolinks:load', function(){
    $('#star').raty({
      size: 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn:   '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png')%>',
      scoreName: 'post[rate]',
      half: true
    });
  })
</script>

app/views/posts/show.html.erb
<h2>詳細</h2>
<table class="table">
  <tbody>
    <tr>
      <td>タイトル</td>
      <td><%= @post.title %></td>
    </tr>
    <tr>
      <td>鑑賞した日時</td>
      <td><%= @post.watched_on.strftime("%Y年 %m月 %d日") %></td>
    </tr>
    <tr>
      <td>鑑賞した劇場</td>
      <td><%= @post.theater %></td>
    </tr>
    <tr>
      <td>コメント</td>
      <td><%= @post.comment %></td>
    </tr>
    <tr>
      <td>レビュー</td>
      <td>
        <div id="rate"></div>
        <script>
          $(document).on('turbolinks:load', function(){
            $('#rate').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn :  '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @post.rate %>,
            });
          });
        </script> 
      </td>
    </tr>
    <tr>
      <td>参考になった！の数</td>
      <td><%= @post.helpfuls.count %></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <% if @post.user_id == current_user.id %>
          <%= link_to '編集する', edit_post_path, class: "btn btn-primary" %>
          <%= link_to '削除する', @post, method: :delete, data: { confirm: "この投稿を削除しますか？"}, class: 'btn btn-danger' %>
        <% else %>
          <% if current_user.already_helpfuled?(@post) %>
            <%= button_to '参考になった！を取り消す', post_helpful_path(@post), method: :delete, class: "btn btn-primary" %>
          <% else %>
            <%= button_to '参考になった！', post_helpfuls_path(@post), class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<% if @posts_of_the_same_name.exists? %>
  <h3>同名のタイトルの映画のレビューに以下の様なものがあります</h3>
  <table class="table table-striped">
    <% @posts_of_the_same_name.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%= post.watched_on %></td>
        <td><%= post.theater    %></td>
        <td><%= post.comment.truncate(13)    %></td>
        <td>
          <div id="star-rate-<%= post.id %>"></div>
          <script>
            $(document).on('turbolinks:load', function(){
              $('#star-rate-<%= post.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn :  '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= post.rate %>,
              });
            });
          </script>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h4>同名のタイトルのレビューなかったわ</h4>
<% end %>

app/views/users/show.html.erb
<h1>じぶんの投稿</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>観賞日</th>
      <th>映画館</th>
      <th>コメント</th>
      <th>評価</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%= post.watched_on %></td>
        <td><%= post.theater    %></td>
        <td><%= post.comment.truncate(13)    %></td>
        <td>
          <div id="star-rate-<%= post.id %>"></div>
          <script>
            $(document).on('turbolinks:load', function(){
              $('#star-rate-<%= post.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn :  '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= post.rate %>,
              });
            });
          </script> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>